### ISSUE TITLE
chatbot/dict.txt: no such file or directory

### ISSUE THREAD

**Issue by Allenxuxu** [kevwan/chatbot#2]
memorystorage.go:80 open /**/**/**/chatbot/dict.txt: no such file or directory

似乎还缺少一些运行必须的配置

**Comment by damingerdai** [comment]
我也遇到这个问题，手动尝试添加`dict.txt`和`idf.txt`,则会出现：

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/wangbin/jiebago/analyse.(*Idf).Load(0xc000010980, 0x33)
        /Users/gming001/go/pkg/mod/github.com/wangbin/jiebago@v0.3.2/analyse/idf.go:37 +0x27c
github.com/wangbin/jiebago/dictionary.LoadDictionary({0x18bb6b0, 0xc000010980}, {0x1264ff3, 0x18})
        /Users/gming001/go/pkg/mod/github.com/wangbin/jiebago@v0.3.2/dictionary/dictionary.go:68 +0xed
github.com/wangbin/jiebago/analyse.(*Idf).loadDictionary(...)
        /Users/gming001/go/pkg/mod/github.com/wangbin/jiebago@v0.3.2/analyse/idf.go:42
github.com/wangbin/jiebago/analyse.(*TagExtracter).LoadIdf(0xc00000d6c8, {0x1264ff3, 0x7})
        /Users/gming001/go/pkg/mod/github.com/wangbin/jiebago@v0.3.2/analyse/tag_extracker.go:64 +0xd5
github.com/kevwan/chatbot/bot/adapters/storage.NewMemoryStorage()
        /Users/gming001/Workspace/daming/go/chatbot/bot/adapters/storage/memorystorage.go:83 +0xdb
github.com/kevwan/chatbot/bot/adapters/storage.NewSeparatedMemoryStorage({0x12658b4, 0xc0000b0050})
        /Users/gming001/Workspace/daming/go/chatbot/bot/adapters/storage/separatedmemorystorage.go:35 +0x65
main.main()
        /Users/gming001/Workspace/daming/go/chatbot/cli/train/train.go:44 +0x146
```
